language: python
cache: pip
python:
  - "2.7"
services:
  - mongodb
env:
  - TEST_SUITE=tests/test_assessment.py
  - TEST_SUITE=tests/test_asset_accessibility.py
  - TEST_SUITE=tests/test_drag_and_drop.py
  - TEST_SUITE=tests/test_logging.py
  - TEST_SUITE=tests/test_qti.py
  - TEST_SUITE=tests/test_repository.py
  - TEST_SUITE=tests/test_restful_items.py
  - TEST_SUITE="-k 'not tests'"

sudo: false

before_install:
  - pip install --upgrade pytest
  - pip install coveralls

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - git submodule update --init --recursive

# command to run tests
script: "python -m pytest -x $TEST_SUITE"

# command to report coverage stats
after_success:
  - coveralls
